### ISSUE TITLE
Inherited Properties

### ISSUE THREAD

**Issue by cyouh95** [glennrosenberg/Dasmoto#2]
Since you've specified `font-family: Helvetica;` for your `body` element, all its children element would automatically inherit this property, so you would not need to specify that again for each of the other elements. It'd also be a good idea to add `font-weight: bold;` there as well since it seems to be a universal property shared by all elements.

https://github.com/glennrosenberg/Dasmoto/blob/master/resources/style.css#L1-L3

**Comment by glennrosenberg** [comment]
I originally left the paragraph style as the default times new roman because the redline document didn't specify but when I reviewed the page it looked unbalanced so I decided to change everything to Helvetica.  I left the styles in the other elements in case I needed to change it back - too much hubris I guess :)

**Comment by glennrosenberg** [comment]
Updated to use inheritance from the body element for font-family and remove the redundancy.
